<div class="copyright">
  <div>&copy <?= $scMetaCopyYears ?>
    <a class='domain' href=" <?= $scMetaCopyLink ?>"><?= $scMetaOgSiteName ?></a>
  </div>
  <div> &nbsp; powered by <a class='scorpio' href='https://scorpiocoding.com' target='_blank'>Quickstart</a>
  </div>
  <div> &nbsp; created by <a class='scorpio' href='https://scorpiocoding.com' target='_blank'>ScorpioCoding.com</a>
  </div>
</div>