<div id="myTopNav" class="topNavBar">
  <div class="hamburger" onclick="openNav()">&#9776;</div>
  <div class="rightNav">
    <a href="/accounts/profile" class="tooltip">
      <i class="fa-solid fa-user"></i>
      <span class="tooltiptext tooltipleft">Your Profile</span>
    </a>
    <a href="/accounts/logout" class="tooltip">
      <i class="fa-solid fa-arrow-right-from-bracket"></i>
      <span class="tooltiptext tooltipleft">Logout</span>
    </a>
  </div>
</div>