<div class="grid-columns-2 container">

  <div>
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>title</th>
          <th>actions</th>
        </tr>
      </thead>
      <?php foreach ($data['posts'] as $post) : ?>
        <tr>
          <td><?= $post['id'] ?></td>
          <td><?= $post['title'] ?></td>
          <td>
            <a href="/blog/edit/<?= $post['id'] ?>"><i class="fa-solid fa-pen-to-square"></i></a>
          </td>
        </tr>
      <?php endforeach ?>

    </table>
  </div>

</div>